default:
  dataconnection:
    driver: 'PostgreSQL Unicode'
    server: 'tacticaltest.kwiqly.com'
    uid: 'backend'
    pwd: 'interlaken'
    port: 5432
    database: 'postgres'
    boolsaschar: 0
    maxvarcharsize: 0

shinyapps:
  dataconnection:
    driver: 'PostgreSQL'
    server: 'tacticaltest.kwiqly.com'
    uid: 'backend'
    pwd: 'interlaken'
    port: 5432
    database: 'postgres'
    boolsaschar: 0
    maxvarcharsize: 0
